export enum PaymentStatusType {
  NEW = 'NEW',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  AUTHORIZED = 'AUTHORIZED',
  REVERSED = 'REVERSED',
  PARTIAL_REFUNDED = 'PARTIAL_REFUNDED',
  REFUNDED = 'REFUNDED',
}
